### PR TITLE
updated to swift 5.2.4

### PR DESCRIPTION
**Pull request by waterskier2007**

### CODE REVIEW

**Comment by waterskier2007** [comment]
@swift-ci test

**Comment by waterskier2007** [comment]
Addresses #176. this is my first PR for this repo so please inform me if I have not taken any necessary steps.

**Comment by shahmishal** [comment]
This issue will be address by https://github.com/apple/swift-docker/pull/175, should we close this PR?

**Comment by waterskier2007** [comment]
@shahmishal I created it simply because the scope of the other PR was tackling multiple things and I didn't know if it was best practice to keep the PRs small and limited in scope. I also figured that having this pr be small might give it a better chance of being merged sooner.

**Comment by waterskier2007** [comment]
I see the other one was merged

**Pull request closed without merging**
