### PR TITLE
Replaced rsync command

### LINKED ISSUE #7: [RFC] Untar directly into root
We can untar directly into the root of the filesystem, so no path modification nor rsync. I think it's slightly more elegant.

https://github.com/swizzlr/docker-swift/blob/master/Dockerfile#L9

### PR DESCRIPTION
**Pull request by hamin**
This PR closes #7

### CODE REVIEW

**Comment by hamin** [comment]
@swizzlr feel free to merge whenever you want. By the way the docker image is already building faster and is leaner than when we start :) Hurray for OSS :)

**Comment by hamin** [comment]
@swizzlr gonna merge this to master :). I want to see if this helps us out in #9

**Comment by swizzlr** [comment]
This is great!

**Comment by Hamza1122H** [comment]
B

**Pull request merged**
