### PR TITLE
[5.2] Add Dockerfile for Ubuntu 20.04, CentOS 8, and Amazon Linux 2. …

### PR DESCRIPTION
**Pull request by shahmishal**
…Also, update the 16.04 and 18.04 Dockerfiles to 5.2.4 release

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by waterskier2007** [comment]
This should address #176

**Comment by tomerd** [comment]
thanks @shahmishal, are we missing an ubuntu 20 slim?

**Comment by tomerd** [comment]
@shahmishal we may also want to merge https://github.com/apple/swift-docker/pull/174 and bring those changes here before we merge this

**Comment by shahmishal** [comment]
@tomerd Should we take #174 in release Dockerfile before it's merged into master Dockerfile?

**Comment by tomerd** [comment]
> @tomerd Should we take #174 in release Dockerfile before it's merged into master Dockerfile?

@shahmishal no but I suggest we do the release after we merge it and then bring it over

**Pull request merged**
