### PR TITLE
<Description> : Upgrading clang to 3.8

### PR DESCRIPTION
**Pull request by Khalian**
<Type> : config

### CODE REVIEW

**Comment by Khalian** [comment]
Solving : https://github.com/swiftdocker/docker-swift/issues/49

**Comment by swizzlr** [comment]
@Khalian what's the officially supported version of Clang from the Swift team? could you find out?

**Comment by Khalian** [comment]
3.9.0 i think. 

http://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz

That being said the higher version available from the canonical repos is 3.8. Hence I put that. 

    Get:21 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [87.2 kB]
    Fetched 24.7 MB in 3min 15s (127 kB/s)
    Reading package lists...
    Reading package lists...
    Building dependency tree...
    Reading state information...
    E: Unable to locate package clang-3.9
    E: Couldn't find any package by glob 'clang-3.9'

**Comment by Khalian** [comment]
Can I go ahead and merging it.

**Comment by swizzlr** [comment]
Yeah, it seems that 3.8 is the "official" version we should be using. Just to be on the safe side, let's bring this change in along with Swift 3.1, which should land very soon. Could you PR this against the 3.1 branch?

**Comment by Khalian** [comment]
Sure.

**Comment by Khalian** [comment]
https://github.com/swiftdocker/docker-swift/pull/65

**Comment by glessard** [comment]
June 12: the tagged version still includes clang-3.6, months after it was deemed obviously too old.

**Pull request closed without merging**
