### PR TITLE
Add Swift 4.1 Dockerfile

### PR DESCRIPTION
**Pull request by florianreinhart**
Is there anything else that needs to be done when adding a new minor version?

### CODE REVIEW

**Comment by andradei** [comment]
Is the build step manual?

**Comment by hamin** [comment]
This looks great to me, @swizzlr if I remember correctly we'll have to make a PR to the official swift docker image repo too right? @lgaches if you don't mind a look at the changes I think should be good to go

**Comment by lgaches** [comment]
looks good.

**Comment by hamin** [comment]
@lgaches awesome, what was the workflow for updating the official docker swift images again? Sorry its been a while :)

**Comment by dsperling** [comment]
Looks good.  Make sure to update the `PROJECT.md` as well.

**Comment by lgaches** [comment]
@hamin after you merge this PR, you need to do a PR to the docker official image. I can do it if you want.

**Comment by hamin** [comment]
@lgaches awesome!! do u mind do the PR to docker official image? Thank you :)

**Comment by lgaches** [comment]
Done

**Comment by hamin** [comment]
@florianreinhart thank you for your PR :)

**Pull request merged**
