### PR TITLE
Added Dockerfiles for Fedora 32 and Fedora Rawhide

### PR DESCRIPTION
**Pull request by tachoknight**
Thanks to the merging of [this PR](https://github.com/apple/llvm-project/pull/1315) Fedora 32 (current) and Fedora Rawhide (always the next version of Fedora) can now be successfully built from master.

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test please

**Comment by tomerd** [comment]
thanks @tachoknight and sorry for slow response time, WWDC taken our attention

**Comment by tachoknight** [comment]
Of course, I totally understand the tremendous amount of work that was going on. :)

**Review by tomerd — APPROVED** [review]
LGTM

**Comment by tomerd** [comment]
@tachoknight which tarballs do you think we should publish from swift.org? 31? 32? both?

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by tachoknight** [comment]
I suggest providing both. Fedora keeps the current and current-1 version as live and updated; once 33 comes out sometime in the fall 31 will drop off. I will provide a 33 file when it’s officially forked from Rawhide (the rolling, always bleeding-edge development version).

**Comment by shahmishal** [comment]
```

  | PASSED_swift-ci_master_fedora_31.log | Jun 29, 2020 5:09:32 PM | 101.18 KB | view
  | PASSED_swift-ci_master_fedora_32.log | Jun 29, 2020 5:03:34 PM | 112.13 KB | view

```

Both passed, going to merge this.

**Comment by shahmishal** [comment]
Thanks @tachoknight!

**Pull request merged**
