### PR TITLE
Windows: update the 5.9 image rules

### PR DESCRIPTION
**Pull request by compnerd**
Update the Dockerfile to address feedback from the docker library maintainers. Install the python package before VS. Add installer validation, which is easier as a series of powershell scripts. This should be a bit more flexible for us now.

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
If possible, it does not need to be in this PR. 

Can we update the ci_test to check windows dockerfiles? 

https://github.com/apple/swift-docker/blob/main/ci_test.py#L47C9-L49C41

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@shahmishal - I think that I got what you were suggesting in the change?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
