### PR TITLE
Add Dockerfile for Swift 4.2

### LINKED ISSUE #114: Swift 4.2 development snapshots
It would be great to have Swift Docker images for Swift 4.2 development snapshots. I think it's good enough to update them manually every or every other week to the latest Swift 4.2 snapshot.

I could update the 4.2 image regularly in this repo. However, I don't know what's needed to merge them into the official Docker images repo.

### PR DESCRIPTION
**Pull request by florianreinhart**
Fixes #114.

### CODE REVIEW

**Review by pepicrft — APPROVED** [review]

**Comment by florianreinhart** [comment]
I'll update this PR for the Swift 4.2 GM once it is released.

**Comment by florianreinhart** [comment]
Updated to the Swift 4.2 release.

I haven't deleted the 4.0 Dockerfile, yet. Let me know if I should create a separate PR for that.

**Comment by Andrewangeta** [comment]
@florianreinhart 
Can we merge this in? Really excited to start using 4.2 now that it's released. Don't want to have to maintain my own private image anymore :P of the dev snapshots.

**Comment by andrewtheis** [comment]
@pepibumur Swift 4.2 released yesterday. Would be great to get this in!

**Comment by hamin** [comment]
thanks @florianreinhart !

**Comment by florianreinhart** [comment]
@hamin Thanks! I will now create a PR to the official Docker image repo.

**Comment by florianreinhart** [comment]
https://github.com/docker-library/official-images/pull/4856

**Pull request merged**
