### PR TITLE
Swift 5.4 nightly support

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Comment by weissi** [comment]
@swift-ci test

**Comment by weissi** [comment]
CC @shahmishal

**Review by shahmishal — APPROVED** [review]
Thanks!

**Comment by weissi** [comment]
same here

```
02:31:24 Error response from daemon: conflict: unable to delete 300e315adb2f (must be forced) - image is referenced in multiple repositories
02:31:24 Error response from daemon: conflict: unable to delete 300e315adb2f (must be forced) - image is referenced in multiple repositories

```

**Comment by weissi** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
Reading state information...
[91mE: Unable to locate package libpython3.6
E: Couldn't find any package by glob 'libpython3.6'
E: Couldn't find any package by regex 'libpython3.6'
```
https://ci.swift.org/job/swift-docker-PR-linux/135/artifact/FAILED_nightly-5.4_ubuntu_16.04.log

**Comment by weissi** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```

  | PASSED_nightly-5.4_amazonlinux_2_slim.log | Feb 2, 2021 6:21:35 PM | 8.71 KB | view
  | PASSED_nightly-5.4_amazonlinux_2.log | Feb 2, 2021 6:25:13 PM | 57.01 KB | view
  | PASSED_nightly-5.4_centos_7_slim.log | Feb 2, 2021 6:14:31 PM | 4.51 KB | view
  | PASSED_nightly-5.4_centos_7.log | Feb 2, 2021 6:19:13 PM | 49.51 KB | view
  | PASSED_nightly-5.4_centos_8_slim.log | Feb 2, 2021 6:08:33 PM | 4.53 KB | view
  | PASSED_nightly-5.4_centos_8.log | Feb 2, 2021 6:12:50 PM | 40.95 KB | view
  | PASSED_nightly-5.4_ubuntu_16.04_slim.log | Feb 2, 2021 6:03:20 PM | 28.02 KB | view
  | PASSED_nightly-5.4_ubuntu_16.04.log | Feb 2, 2021 6:06:53 PM | 58.73 KB | view
  | PASSED_nightly-5.4_ubuntu_18.04_slim.log | Feb 2, 2021 5:57:27 PM | 31.46 KB | view
  | PASSED_nightly-5.4_ubuntu_18.04.log | Feb 2, 2021 6:01:04 PM | 65.28 KB | view
  | PASSED_nightly-5.4_ubuntu_20.04_slim.log | Feb 2, 2021 5:51:38 PM | 31.38 KB | view
  | PASSED_nightly-5.4_ubuntu_20.04.log | Feb 2, 2021 5:55:12 PM | 56.78 KB | view


```

**Pull request merged**
