### PR TITLE
Adding permissions for Core Foundation library.

### PR DESCRIPTION
**Pull request by Khalian**

### CODE REVIEW

**Comment by Khalian** [comment]
Solution to https://github.com/swiftdocker/docker-swift/issues/70

**Comment by hamin** [comment]
@swizzlr I'm ok with this. Although I myself usually use root for docker we shouldn't necessarily stop ppl for being able to use swift with a non-root users in the docker image. This PR I think solves the issue raised #70

**Comment by Khalian** [comment]
Can we merge this ?

**Comment by Khalian** [comment]
@hamin Can we merge this?

**Comment by hamin** [comment]
@Khalian can u make just one change... instead of adding a new `RUN` statement can you append that to the https://github.com/Khalian/docker-swift/blob/d86c55c3003b30184f0fa0d9792a39f8a43b13d8/Dockerfile#L58 w/ `&&` as the last statement run? Once you go ahead and do that i'll merge. And keep your comment in there if you can...super helpful for short term memories :)

**Comment by Khalian** [comment]
@hamin Done.

**Pull request merged**
