### PR TITLE
Adding support for shared library path lookup.

### PR DESCRIPTION
**Pull request by Khalian**

### CODE REVIEW

**Comment by Khalian** [comment]
@hamin Can we merge this?

**Comment by Khalian** [comment]
@hamin Would you mind taking a look at this ?

**Comment by hamin** [comment]
@khalian trying to understand why this was needed. What's the issue that this is trying to solve? Was this introduced in a more recently? Thanks.

**Comment by Khalian** [comment]
@hamin It solves this problem https://github.com/swiftdocker/docker-swift/issues/75

**Comment by hamin** [comment]
@khalian ah awesome, is there an example that I can try with? This looks good though

**Pull request closed without merging**
