### PR TITLE
New Debian 11/bullseye docker file

### PR DESCRIPTION
**Pull request by schafdog**
Based on Ubuntu 22.04

### CODE REVIEW

**Comment by schafdog** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@schafdog Thanks for adding Debian 11 Dockerfile. Does the Docker image work with `./swift/utils/build-toolchain` script?

**Comment by schafdog** [comment]
Hi @shahmishal 

I have only tried the build-script --prefix=buildbot_incremental_linux

Which parameters should I run the build-toolchain script with?

**Comment by shahmishal** [comment]
for example: `./swift/utils/build-toolchain swift --test`

**Comment by schafdog** [comment]
hmm it doesn't seem like the build-script has genererated the expected result. But I am not seeing an error/crash anywhere in the logs. How much memory does the build script requires?

Will try again but if you have any hints for debugging this, I would appreciate.

**Comment by schafdog** [comment]
I have successfully built using the build-script and your sugested command:
End of the log looks like this:

```
Total Duration: 13564.91
--- Build Script Analyzer ---
Build Script Log: /home/build-user/build/.build_script_log
Build Percentage 	 Build Duration (sec) 	 Build Phase
================ 	 ==================== 	 ===========
32.0%             	 4335.67               	 linux-x86_64-llvm-build
18.6%             	 2523.67               	 linux-x86_64-swift-build
10.8%             	 1471.53               	 linux-x86_64-swift-test
5.4%              	 733.46                	 linux-x86_64-lldb-build
4.0%              	 537.5                 	 Running tests for swiftdocc
3.6%              	 486.35                	 Running tests for swiftpm
3.5%              	 474.41                	 Running tests for swiftdriver
2.8%              	 384.82                	 Building swiftpm
2.3%              	 306.94                	 linux-x86_64-lldb-test
1.9%              	 257.22                	 linux-x86_64-foundation-test
1.8%              	 250.63                	 Building sourcekitlsp
1.7%              	 231.86                	 Installing swiftpm
1.6%              	 220.98                	 Building swiftdocc
1.4%              	 190.78                	 Installing swiftdocc
1.1%              	 152.42                	 linux-x86_64-foundation-build
1.1%              	 142.57                	 linux-x86_64-libicu-build
0.9%              	 120.05                	 Building swiftdriver
0.9%              	 117.26                	 linux-x86_64-package
0.9%              	 115.46                	 Building benchmarks
0.8%              	 114.34                	 Installing swiftdriver
0.4%              	 55.8                  	 Running tests for sourcekitlsp
0.4%              	 49.53                 	 linux-x86_64-foundation-install
0.3%              	 47.16                 	 linux-x86_64-llbuild-build
0.3%              	 46.04                 	 linux-x86_64-llbuild-test
0.3%              	 40.8                  	 Building indexstoredb
0.3%              	 39.08                 	 linux-x86_64-libicu-test
0.2%              	 30.12                 	 linux-x86_64-libdispatch-test
0.1%              	 18.24                 	 Running tests for indexstoredb
0.1%              	 17.59                 	 linux-x86_64-xctest-test
0.1%              	 16.4                  	 linux-x86_64-libdispatch-build
0.1%              	 10.89                 	 linux-x86_64-llvm-install
0.0%              	 5.45                  	 linux-x86_64-xctest-build
0.0%              	 5.23                  	 Running tests for cmark
0.0%              	 4.14                  	 Building cmark
0.0%              	 3.21                  	 linux-x86_64-llbuild-install
0.0%              	 2.89                  	 Installing sourcekitlsp
0.0%              	 1.57                  	 linux-x86_64-swift-install
0.0%              	 1.08                  	 Running tests for benchmarks
0.0%              	 0.56                  	 linux-x86_64-lldb-install
0.0%              	 0.24                  	 Installing swiftdoccrender
0.0%              	 0.22                  	 linux-x86_64-libicu-install
0.0%              	 0.19                  	 linux-x86_64-xctest-install
0.0%              	 0.19                  	 Cleaning swiftpm
0.0%              	 0.11                  	 linux-x86_64-libdispatch-install
0.0%              	 0.1                   	 Cleaning swiftdriver
0.0%              	 0.06                  	 linux-x86_64-llvm-test
0.0%              	 0.04                  	 linux-x86_64-extractsymbols
0.0%              	 0.03                  	 merged-hosts-lipo-core
0.0%              	 0.03                  	 merged-hosts-lipo
Total Duration: 13564.91
```
Is this what is to be expected?

**Comment by shahmishal** [comment]
Yes, thanks!

**Pull request merged**
