### PR TITLE
Install python3-pip in ubuntu and AWS container

### PR DESCRIPTION
**Pull request by justice-adams-apple**
Install python3 pip in the nightly containers so the rebranch jobs can install their dependencies

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
cc @shahmishal

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@shahmishal seems like the test itself is broken here 
```
KeyError: 'http_proxy'
```

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Pull request merged**
