### PR TITLE
[README] Create symlink to Readme.md to docs/README.md to avoid dupli…

### PR DESCRIPTION
**Pull request by shahmishal**
…cation

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by ianpartridge** [comment]
Hi @shahmishal it looks like the keyserver is timing out... these can be quite flaky unfortunately.

Which keyservers are the Swift keys found on?  Could you upload the keys to more keyservers?

Then perhaps we could do something like this in the `Dockerfile`s:

```bash
gpg --quiet --keyserver pgp.mit.edu --recv-keys "$key" ||
gpg --quiet --keyserver keyserver.pgp.com --recv-keys "$key" ||
gpg --quiet --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"
```

to try a few different ones.

**Comment by hamin** [comment]
Hmm interesting didn't realize key servers would be an issue here. Any particular reason for their flakiness @ianpartridge ?

**Comment by ianpartridge** [comment]
https://github.com/docker-library/official-images/issues/4252 has the gory details, I think.

**Comment by shahmishal** [comment]
@ianpartridge I was testing out CI integration, failure is due to limited access to outside network.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Network issue resolved I will look into getting the key on to multiple servers.
@hamin @ianpartridge Are you ok with me merging this?

**Comment by ianpartridge** [comment]
Thanks @shahmishal.  Looking at the console log of the CI run it didn't build the 4.2 Dockerfile?

**Comment by shahmishal** [comment]
@ianpartridge I was thinking about using, to avoid from running into network issue with keyserver. 

```
$ wget -q -O - https://swift.org/keys/all-keys.asc | \
  gpg --import -
```

Thoughts?

**Comment by ianpartridge** [comment]
If that's more reliable then great!

**Pull request merged**
