### PR TITLE
Shippable builds for Continuous Integration

### PR DESCRIPTION
**Pull request by Khalian**
An example of a successful build https://app.shippable.com/runs/586365aff6c7101000c352de/1/console

Shippable is heavily optimized for docker builds (keeping layers intact across builds and better integration with docker hub) as compared to incumbents Travis CI. 

Now you can monitor PRs or the builds directly so as to trust changes without having to manually build them. 

Of course I don't know which registry to add to, so I did not update post ci steps.

### CODE REVIEW

**Comment by Khalian** [comment]
screen shot 2016-12-27 at 11 24 01 pm

**Comment by swizzlr** [comment]
Apologies for missing this, apparently the repository was unwatched! This looks great, I'll authorize this for the org. Thank you, Khalian!

**Comment by swizzlr** [comment]
@Khalian could you push a touch commit to trigger a new shippable build? I've enabled Shippable for this org.

**Comment by swizzlr** [comment]
By the way, we're using Docker hub for automated builds so I don't think we'll need to do this for deploy, yet.

**Comment by Khalian** [comment]
You can write post ci workflows in Shipp able that allows automatic uploads to docker hub.

**Pull request merged**
