### PR TITLE
Add unzip to nightly 5.7 Dockerfile

### PR DESCRIPTION
**Pull request by shahmishal**
https://github.com/apple/swift-docker/pull/300/

### CODE REVIEW

**Comment by shahmishal** [comment]
cc: @fabianfett

**Comment by fabianfett** [comment]
woohoo 🙌

**Review by tomerd — APPROVED** [review]
looks good, i think we originally tried to sort deps alphabetically so that they are easier to find, but just a nit

**Comment by shahmishal** [comment]
I will follow up with new PR to sort them.

**Pull request merged**
