### PR TITLE
refactor nightly docker files

### PR DESCRIPTION
**Pull request by tomerd**
motivation: easier to reason about deps

changes:
* reorder deps alphabetically
* remove libatomic from deps list since not needed any longer
* use /etc/bashrc in fedora based distros
* user echo -e on fedora based distros
* fix small alignemtn issues

### CODE REVIEW

**Review by shahmishal — APPROVED** [review]
Thanks for cleaning up the Dockerfile and adding slim config.

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by tomerd** [comment]
@swift-ci Please test

**Review by drexin — APPROVED** [review]

**Comment by shahmishal** [comment]
```
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.2/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/swift-ci/master/amazon-linux/2: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.0/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/swift-ci/master/centos/8: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.2/ubuntu/18.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.1/ubuntu/18.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/ubuntu/18.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/ubuntu/18.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.0/ubuntu/16.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.0/ubuntu/18.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/4.1: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/4.0: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/4.2/ubuntu/18.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.2/ubuntu/16.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/centos/8: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.3/ubuntu/18.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.3/ubuntu/16.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.3/ubuntu/18.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/swift-ci/master/ubuntu/19.10: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/ubuntu/20.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.3/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.2/ubuntu/18.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.2/ubuntu/18.04: FAILED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/swift-ci/master/ubuntu/20.04: FAILED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/amazonlinux/2: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.1/ubuntu/18.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/pgp-happy-eyeballs: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/ubuntu/16.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.2/ubuntu/18.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.2/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-5.2/ubuntu/16.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.0/ubuntu/18.04: FAILED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/3.1: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/4.2/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.1/ubuntu/16.04/slim: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/5.1/ubuntu/16.04: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/swift-ci/master/debian/9: PASSED
/home/buildnode/jenkins/workspace/swift-docker-PR-linux/nightly-master/ubuntu/20.04: PASSED
```

**Comment by tomerd** [comment]
@shahmishal failures seem unrelated to the changes? seems docker related?

**Pull request merged**
