### PR TITLE
Add support for Swift 4.2.1 - Ubuntu 18.04

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by florianreinhart** [comment]
What‘s the reason for setting the time zone to LA? I think it should be UTC, which is the default for Docker containers.

**Comment by shahmishal** [comment]
@florianreinhart good catch, I will remove it.

**Review by hamin — APPROVED** [review]
This looks great!

**Review by ianpartridge — APPROVED** [review]
Looks good to me.  It would be best if we can sort out the flaky keyserver issues as they affected me when I tried `docker build`ing this to test it out.

**Pull request merged**
