### PR TITLE
Add Swift 5.9 Dockerfiles

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by MarcoEidinger** [comment]
@shahmishal do you know when 5.9 tag and respective Dockerfile link will be available on https://hub.docker.com/_/swift/ ?

**Comment by shahmishal** [comment]
Waiting for https://github.com/docker-library/official-images/pull/15389

**Comment by kingttdk** [comment]
BankStatementChequing

**Pull request merged**
