### PR TITLE
Add support for Swift 5.4 Release

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by damuellen** [comment]
Is this not the wrong Python Version ? At least the nightly 5.4 builds use python 3.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```

  | PASSED_5.4_amazonlinux_2_slim.log | Apr 27, 2021 7:29:20 PM | 6.18 KB | view
  | PASSED_5.4_amazonlinux_2.log | Apr 27, 2021 7:32:41 PM | 57.85 KB | view
  | PASSED_5.4_centos_7_slim.log | Apr 27, 2021 7:21:50 PM | 2.74 KB | view
  | PASSED_5.4_centos_7.log | Apr 27, 2021 7:27:14 PM | 37.28 KB | view
  | PASSED_5.4_centos_8_slim.log | Apr 27, 2021 7:16:15 PM | 2.70 KB | view
  | PASSED_5.4_centos_8.log | Apr 27, 2021 7:20:07 PM | 39.59 KB | view
  | PASSED_5.4_ubuntu_16.04_slim.log | Apr 27, 2021 7:11:09 PM | 26.29 KB | view
  | PASSED_5.4_ubuntu_16.04.log | Apr 27, 2021 7:14:43 PM | 56.98 KB | view
  | PASSED_5.4_ubuntu_18.04_slim.log | Apr 27, 2021 7:04:40 PM | 29.67 KB | view
  | PASSED_5.4_ubuntu_18.04.log | Apr 27, 2021 7:08:50 PM | 63.46 KB | view
  | PASSED_5.4_ubuntu_20.04_slim.log | Apr 27, 2021 6:58:23 PM | 29.76 KB | view
  | PASSED_5.4_ubuntu_20.04.log | Apr 27, 2021 7:01:52 PM | 55.28 KB | view
 


```

**Pull request merged**
