### PR TITLE
Ubuntu 20.04: add `python3-dev` and `python3-distutils`

### PR DESCRIPTION
**Pull request by compnerd**
These packages are needed to build Swift successfully with Python 3.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by shahmishal — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
```
PASSED_swift-ci_master_ubuntu_20.04.log
```

**Pull request merged**
