### PR TITLE
Allow SwiftPM to function inside image

### PR DESCRIPTION
**Pull request by zwaldowski**
Installs `curl` in the image so that `swift build` and `swift test` work.

### CODE REVIEW

**Comment by ChasonTang** [comment]
+1

**Comment by hamin** [comment]
@zwaldowski thanks just saw this :). Hmm so I'm completely fine merging this...just wondering how I should deal with the existing tags for `3.0.0` and `3.0.1` on docker hub. Thoughts?

**Comment by zwaldowski** [comment]
@hamin Not an expert, but I see no harm in re-tagging? Makes it complicated for 3.0.0, not sure what to do there.

**Comment by hamin** [comment]
@zwaldowski ok merged and there's a new `3.0.1` tag on Docker hub. Unfortunately `3.0.0` still has that bug. But I think its ok for now :). Thanks for the PR @zwaldowski

**Pull request merged**
