### PR TITLE
Relicence to Apache License, Version 2

### PR DESCRIPTION
**Pull request by ianpartridge**
We are planning to move this project upstream, to become an official swift.org project hosted in the Apple GitHub organisation.

As all [swift.org projects use the Apache Licence, Version 2](https://swift.org/community/#license), this PR relicenses this project accordingly. Relicensing is a prerequisite for moving this project upstream.

Consent of the contributors to this project will be collected below.  Please comment with +1 if you consent.

### CODE REVIEW

**Comment by ianpartridge** [comment]
+1

**Comment by florianreinhart** [comment]
+1

**Comment by ianpartridge** [comment]
@swizzlr @hamin @Khalian @lgaches @briancroom @zwaldowski @CrowdHailer @foulkesjohn @rpitonak @tid-kijyun @aidansteele @pyros2097 @bppr @antonmes @gabhi @bre7 @thii @bamx23 @fud please give your consent to this relicensing.

**Comment by lgaches** [comment]
+1

**Review by lgaches — APPROVED** [review]

**Comment by thii** [comment]
+1

**Review by thii — APPROVED** [review]

**Comment by bre7** [comment]
+1

**Review by bre7 — APPROVED** [review]

**Review by rpitonak — APPROVED** [review]
+1

**Comment by zwaldowski** [comment]
I give my consent.

**Comment by hamin** [comment]
👍

**Comment by foulkesjohn** [comment]
👍

**Comment by briancroom** [comment]
👍

**Comment by tid-kijyun** [comment]
👍

**Comment by ianpartridge** [comment]
Update: consent has been given by 11 out of 21 committers so far. Thank you everyone!

We would still like to hear from @swizzlr @Khalian @CrowdHailer @aidansteele @pyros2097 @bppr @antonmes @gabhi @bamx23 and @fud.

The most important people are @swizzlr @Khalian @aidansteele and @bamx23 because they contributed changes to the `Dockerfile`s which are still present in `master` today.

The contributions from @CrowdHailer @pyros2097 @bppr @antonmes @gabhi and @fud are either no longer present in `master` or were README fixes. As we will be rewriting the README anyway that is no problem.

I have emailed @swizzlr @aidansteele and @bamx23 to ask them to take a look at this PR. Does anyone have an email address or other contact method for @Khalian? I sent him a LinkedIn connection request but no response yet.

**Comment by aidansteele** [comment]
+1. Sorry for the delay (and great work)

**Comment by ghost** [comment]
+1. Oops didn't know i was a contributor. Was wondering why i was getting this notification.

**Comment by swizzlr** [comment]
+1 do it!

**Comment by fud** [comment]
+1

**Comment by ianpartridge** [comment]
Update: consent has been given by **15 out of 21** committers so far. Thank you everyone!

We would still like to hear from @Khalian @CrowdHailer @bppr @antonmes @gabhi and @bamx23.

The most important people are @Khalian and @bamx23 because they contributed changes to the Dockerfiles which are still present in master today.

I have emailed @bamx23 to ask them to take a look at this PR. Does anyone have an email address or other contact method for @Khalian?

Thanks everyone for your support - hopefully we can track down the last few people :)

**Comment by Khalian** [comment]
+1. I consent to move this project as an official swift.org project.

**Comment by antonmes** [comment]
+1

**Comment by ianpartridge** [comment]
Update: consent has been given by **17 out of 21** committers so far. Thank you everyone!

We would still like to hear from @CrowdHailer @bppr @gabhi and @bamx23.

The most important person is @bamx23 because he contributed [a commit](https://github.com/swiftdocker/docker-swift/commit/30403046da8238bd781e7af2eb0a2f10a21a8a22) to the `Dockerfile` which is still (indirectly) present in `master` today.

I have emailed @bamx23 to ask them to take a look at this PR, but I haven't had a response yet.

Thanks everyone for your support - hopefully we can track down the last few people :)

**Comment by CrowdHailer** [comment]
+1

**Comment by bamx23** [comment]
+1  (sorry for such delay in answering)

**Comment by ianpartridge** [comment]
Update: consent has been given by **19 out of 21** committers. Thank you everyone!

We would still like to hear from @bppr and @gabhi, for completeness, but I don't believe we need their explicit consent to go ahead.

@bppr made a [one-line change](https://github.com/swiftdocker/docker-swift/commit/d6feaaa4a2ea86e7cab99d45041e6fc69da4d285) to update the development snapshot version, back in the Swift 3 days. This change is no longer present in `master` for some years.
@gabhi [tweaked the README](https://github.com/swiftdocker/docker-swift/commit/5ec58e9663fc6a75ab62c4be09f2294ed074a265) back in 2016.

I think we should go ahead and merge. @swizzlr / @hamin / @florianreinhart - would you like to merge this?

**Comment by hamin** [comment]
@ianpartridge done!

**Pull request merged**
