### PR TITLE
Swift 4 snapshot support

### PR DESCRIPTION
**Pull request by lgaches**

### CODE REVIEW

**Comment by hamin** [comment]
@swizzlr @lgaches I'd thi working now? I tried it a few weeks ago and the key verification was failing

**Comment by lgaches** [comment]
@hamin yes it's working fine for me ( https://hub.docker.com/r/lgaches/docker-swift/ ). I used this image to do some tests.

**Comment by hamin** [comment]
@lgaches interesting, the fingerprinting wasn't working for me when I tried it and I had to comment that part out. Perhaps they've updated that?

**Comment by hamin** [comment]
@lgaches thanks for the PR btw :)

**Comment by hamin** [comment]
FYI @swizzlr @lgaches I just updated /cc DockerHub automated builds. I added `latest` which would track `master` branch /cc @mbrandonw

**Pull request merged**
