### PR TITLE
CentOS: add diffutils

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @drexin @shahmishal

**Review by drexin — APPROVED** [review]
LGTM

**Comment by drexin** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]
LGTM! Thanks

**Comment by shahmishal** [comment]
`[PASSED] - /home/buildnode/jenkins/workspace/swift-docker-PR-linux/swift-ci/master/centos/8`

**Pull request merged**
