### PR TITLE
Swift 5.10: Adding Slim Dockerfiles for new distros

### PR DESCRIPTION
**Pull request by etcwilde**
Adding new Swift 5.10 slim Dockerfiles
 - Ubuntu 24.04
 - Ubuntu 23.10
 - Fedora 39
 - Debian 12

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by etcwilde** [comment]
It looks like all of the test failures were keyserver timeouts.

**Comment by etcwilde** [comment]
@swift-ci please test

**Comment by tibz7** [comment]
Hello, I have seen that the bookworm-slim exists but is not pushed to the registry, is it possible to add it ?

**Pull request merged**
