### PR TITLE
Add requirements.txt file for nightly image

### PR DESCRIPTION
**Pull request by justice-adams-apple**
## In This PR
* Install requirements file into the docker image itself
* build the docker image withe the surrounding context as part of PR testing

### CODE REVIEW

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Comment by justice-adams-apple** [comment]
@swift-ci test

**Review by shahmishal — APPROVED** [review]

**Pull request merged**
