### PR TITLE
Update the key to swift.org for Dockerfile

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by ianpartridge — COMMENTED** [review]
Do we have to add `wget` to the images? Is `curl` already available instead?

**Comment by shahmishal** [comment]
Let me update it to use curl

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
