### PR TITLE
Add CentOS 7 to swift-ci

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
We can probably remove some of the packages that are being installed. I'll check and update the PR.

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
Removed a bunch of packages. Should be ready for review now.

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
PASSED_swift-ci_master_centos_7.log
```
https://ci.swift.org/job/swift-docker-PR-linux/103/artifact/PASSED_swift-ci_master_centos_7.log

**Comment by shahmishal** [comment]
Thanks @drexin

**Comment by 1oo7** [comment]
⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️
This makes me so happy! 😭
⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️⚜️

**Comment by 1oo7** [comment]
BTW—when can we expect there to be a CentOS 7 docker image for Swift? (Not swift-ci but the main one)

**Pull request merged**
